version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: postgres-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_test
      POSTGRES_DB: postgres
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./scripts/init-test-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  subscription-service-test:
    build:
      context: .
      dockerfile: docker/subscription.Dockerfile
    container_name: subscription-service-test
    ports:
      - "3333:3000"
    depends_on:
      postgres-test:
        condition: service_healthy
    environment:
      NODE_ENV: test
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres_test@postgres-test:5432/subscriptions_test_db?schema=subscriptions
      JWT_SECRET: test-jwt-secret-32-chars-minimum
      JWT_REFRESH_SECRET: test-jwt-refresh-secret-32-chars
      JWT_EXPIRES_IN: 1h
      JWT_REFRESH_EXPIRES_IN: 7d
      PAYMENT_SERVICE_URL: http://payment-service-test:3001
      PAYMENT_SERVICE_API_KEY: test-payment-api-key
      WEBHOOK_SECRET: test-webhook-secret-32-chars-min
      CORS_ORIGINS: "*"
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  payment-service-test:
    build:
      context: .
      dockerfile: docker/payment.Dockerfile
    container_name: payment-service-test
    ports:
      - "3334:3001"
    depends_on:
      postgres-test:
        condition: service_healthy
    environment:
      NODE_ENV: test
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres_test@postgres-test:5432/payments_test_db?schema=payment
      API_KEY: test-payment-api-key
      WEBHOOK_SECRET: test-webhook-secret-32-chars-min
      SUBSCRIPTION_SERVICE_WEBHOOK_URL: http://subscription-service-test:3000/v1/webhooks/payment
      PAYMENT_SUCCESS_RATE: 80
      PAYMENT_PROCESSING_DELAY_MS: 1000
      CORS_ORIGINS: "*"
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  postgres_test_data:

networks:
  test-network:
    driver: bridge

